#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run test:ci
npm audit
docker run \
    --rm \
    -e SONAR_HOST_URL="http://host.docker.internal:9000" \
    -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=shop-angular" \
    -e SONAR_LOGIN="sqp_12440acb2ff317a89c7583350bdc8ab4e81fd0f8" \
    -v "/projects/EPAM/Courses/devops-fundamentals-labs/lab_3/shop-angular-cloudfront:/usr/src" \
    sonarsource/sonar-scanner-cli
